name: Cynthia Zanoni
description: I work for the internets and love open web
meta_description: "Blog de Cynthia Zanoni, evangelista de tecnologias open web, organizadora do Mobile Summit e fundadora do WoMakersCode.org"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 5
baseurl: /
domain_name: 'http://cyz.github.io'
google_analytics: 'UA-58464382-1'
gems: [jekyll-paginate]

url:            'http://cyz.github.io'
author:         'Cynthia Zanoni'
