# Site settings
title: Cynthia Zanoni
header-img: img/home-bg.jpg
email: cynthiazanoni@gmail.com
description: "Cynthia Zanoni, desenvolvedora front-end e mobile."
baseurl: "cyz.github.io"
url: "cyz.github.io"
twitter_username: cynthia_zanoni
github_username:  cyz
facebook_username:  cynthiazanoni

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
